import type { Metadata } from "next";
import React from 'react'
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>page</div>
  )
}

export default page